# table name
game_data = 'game_data'
prediction_data = 'prediction_data'

# column name
game_id = 'game_id'
play_time = 'play_time'
am_pm = 'AM_PM'
host_id = 'host_id'
guest_id = 'guest_id'
host_score = 'host_score'
guest_score = 'guest_score'
national_host_point_spread = 'national_host_point_spread'
win_if_meet_spread_point = 'win_if_meet_spread_point'
response_ratio_if_hit_spread_point = 'response_ratio_if_hit_spread_point'
national_total_point_threshold = 'national_total_point_threshold'
local_host_point_spread = 'local_host_point_spread'
local_total_point_threshold = 'local_total_point_threshold'
local_host_point_spread_response_ratio = 'local_host_point_spread_response_ratio'
local_total_point_threshold_response_ratio = 'local_total_point_threshold_response_ratio'
local_origin_guest_response_ratio = 'local_origin_guest_response_ratio'
local_origin_host_response_ratio = 'local_origin_host_response_ratio'
guest = 'guest'
host = 'host'

# prediction
percentage_national_point_spread_guest = 'percentage_national_point_spread_guest'
percentage_national_point_spread_host = 'percentage_national_point_spread_host'
population_national_point_spread_guest = 'population_national_point_spread_guest'
population_national_point_spread_host = 'population_national_point_spread_host'

percentage_national_total_point_guest = 'percentage_national_total_point_guest'
percentage_national_total_point_host = 'percentage_national_total_point_host'
population_national_total_point_guest = 'population_national_total_point_guest'
population_national_total_point_host = 'population_national_total_point_host'

percentage_local_point_spread_guest = 'percentage_local_point_spread_guest'
percentage_local_point_spread_host = 'percentage_local_point_spread_host'
population_local_point_spread_guest = 'population_local_point_spread_guest'
population_local_point_spread_host = 'population_local_point_spread_host'

percentage_local_total_point_guest = 'percentage_local_total_point_guest'
percentage_local_total_point_host = 'percentage_local_total_point_host'
population_local_total_point_guest = 'population_local_total_point_guest'
population_local_total_point_host = 'population_local_total_point_host'

percentage_local_original_guest = 'percentage_local_original_guest'
percentage_local_original_host = 'percentage_local_original_host'
population_local_original_guest = 'population_local_original_guest'
population_local_original_host = 'population_local_original_host'
