gambling:
  ratio_per_game: 1.75
  bet_base: 100
  combination: 1
stratagy_size: 20
support_strategy:
# true: support table strategy
  linear_response: true
  fibonacci_base: true
  foo_double: true
  kelly: false
DB:
  host: "192.168.31.61"
  port: 3306
  user: "allen"
  password: "password"
  schema: "gambling_simulation"