ratio_per_game: 1.75
bet_base: 100
stratagy_size: 20
support_strategy:
  - linear_response
  - fibonacci_base
  - foo_double
DB:
  host: "192.168.31.61"
  port: 3306
  user: "allen"
  password: "password"
  schema: "gambling_simulation"