logging:
  level: "DEBUG"

gambling:
  default_ratio_per_game: 1.75
  bet_base: 100
  combination: 1

stratagy_size: 20
support_strategy:
  # true: support table strategy
  linear_response: true
  fibonacci_base: true
  foo_double: true
  kelly: false

banker:


strategy_provider:
  put_strategy:
    linear_response:
      - lose_count
      - response_ratio
    fibonacci_base:
      - lose_count
    foo_double:
      - lose_count
    kelly:
      - remaining_unit
  bet_strategy:
    random: []
    keep_false: []
    keep_true: []
    low_of_large:
      - game_history

DB:
  host: "192.168.99.31"
  port: 3306
  user: "allen"
  password: "password"
  schema: "gambling_simulation"

mongoDb:
  host: 127.0.0.1
  port: 27017